private
rssXML
	"Note this is modifed for the purpose of the test. normally there would be a <channel> wrapper around the feed.
	for Rss parsing see:
		 http://ss3.gemstone.com/ss/TopFeeder"
	
	^ '<?xml version="1.0" encoding="UTF-8"?>
<!-- generator="wordpress/2.0.2" -->
<rss version="2.0" 
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	>

	<title>Black Bag Operations Network</title>
	<atom:link href="http://www.blackbagops.net/feed/" rel="self" type="application/rss+xml" />
	<link>http://www.blackbagops.net</link>
	<description>Weapons and Intelligence in the War Against "Them"</description>
	<pubDate>Tue, 27 Feb 2007 03:44:13 +0000</pubDate>
	<generator>http://wordpress.org/?v=2.0.2</generator>
	<language>en</language>
</rss>'